cd ../src/data
python move_video.py --src "/data/u_2359629761/yy_datasets/hub/datasets--mjuicem--StreamingBench/snapshots/48872fa707124474ce4c5172ddc58efb8bc88058/StreamingBench/real" --dest "/data/u_2359629761/yy_datasets/hub/datasets--mjuicem--StreamingBench/snapshots/48872fa707124474ce4c5172ddc58efb8bc88058/StreamingBench/videos"
# python move_video.py --src "../../data/omni" --dest "./videos"
# python move_video.py --src "../../data/sqa" --dest "./videos"
# python move_video.py --src "../../data/proactive" --dest "./videos"
# python modify_video_path.py --src "./questions_real.json"
# python modify_video_path.py --src "./questions_omni.json"
# python modify_video_path.py --src "./questions_sqa.json"
# python modify_video_path.py --src "./questions_proactive.json"
# python modify_video_path.py --src "./questions_proactive_50.json"